---
title: "Lab5"
author: "Jayson De La O"
format: html
editor: visual
---

```{r}
library(data.table)
library(dtplyr)
library(dplyr)
library(R.utils)
```

```{r}
if (!file.exists("met_all.gz"))
  download.file(
    url = "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
    destfile = "met_all.gz",
    method   = "libcurl",
    timeout  = 60
    )
met <- data.table::fread("met_all.gz")
```

```{r}
stations <- fread("ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv")
stations[, USAF := as.integer(USAF)]
```

```{r}
# Dealing with NAs and 999999
stations[, USAF   := fifelse(USAF == 999999, NA_integer_, USAF)]
stations[, CTRY   := fifelse(CTRY == "", NA_character_, CTRY)]
stations[, STATE  := fifelse(STATE == "", NA_character_, STATE)]
```

```{r}
# Selecting the three relevant columns, and keeping unique records
stations <- unique(stations[, list(USAF, CTRY, STATE)])
```

```{r}
# Dropping NAs
stations <- stations[!is.na(USAF)]
```

```{r}
# Removing duplicates
stations[, n := 1:.N, by = .(USAF)]
stations <- stations[n == 1,][, n := NULL]
```

```{r}
met
stations
str(met)
```

```{r}
met <- met[,
  .(USAFID, WBAN, year, month, day, hour, min, lat, lon, elev,
    wind.sp, temp, atm.press)]


```

```{r}
dim(met)
dim(stations)
```

```{r}
metmerge <- merge(
  # Data
  x     = met,      
  y     = stations, 
  # List of variables to match
  by.x  = "USAFID",
  by.y  = "USAF", 
  # Which obs to keep?
  all.x = TRUE,      
  all.y = FALSE
  )
head(metmerge[, list(USAFID, WBAN, STATE)], n = 4)
dim(metmerge)
```

```{r}
metmerge
```

Median for wind speed is 2.1, median of temp is 23.5, and median of atmospheric pressure is 1014.1. The three weather stations that represent the continental US 720113(temp), 690150(wind) , and 690150(atm). The stations with the median atm.press and wind speed were the same, but the median temp station did not coincide with the others.

```{r}
quantile(metmerge$wind.sp,probs=.5,na.rm=TRUE)
quantile(metmerge$temp,probs=.5,na.rm=TRUE)
quantile(metmerge$atm.press,probs=.5,na.rm=TRUE)





```

```{r}
stationt <- metmerge[which.min(abs(metmerge$temp- quantile(metmerge$temp,probs=.5,na.rm=TRUE) )) ]

stationt

 stationw<- metmerge[which.min(abs(metmerge$wind.sp- quantile(metmerge$wind.sp,probs=.5,na.rm=TRUE) )) ]
stationw

stationa<- metmerge[which.min(abs(metmerge$atm.press- quantile(metmerge$atm.press,probs=.5,na.rm=TRUE) )) ]
stationa


```

```{r}
med.temp <-median(metmerge$temp, na.rm=TRUE)
med.wind <-median(metmerge$wind.sp, na.rm=TRUE)
med.press <-median(metmerge$atm.press, na.rm=TRUE)


```
